### ISSUE TITLE
Undefined symbols for architecture i386:   "_OBJC_CLASS_$_Sinch", referenced from:       objc-class-ref in libSinchService.a(SINService.o)

### ISSUE THREAD

**Issue by danghung24031992** [relatedcode/RealtimeChat#44]
I'm not running application . please!!!

**Comment by relatedcode** [comment]
@danghung24031992 Please make sure, that you are using the latest version. Furthermore please run both `pod install` and `pod update` before opening the project in Xcode. Lastly please open *app.xcworkspace* instead of *app.xcodeproj*.

Sorry but I don't have any further ideas here. For me it's working perfectly fine.
